server:
  port: 18087

## **********************************************************
##   Elasticsearch Settings
## **********************************************************
elasticsearch:
  data:
    source:
      # es link
      host: http://172.30.6.31:9208
      # userName if elasticsearch open ssl
      username:
      # password if elasticsearch open ssl
      password:
      max_connect_total: 30
      max_connect_per_route: 10
      connection_request_timeout_millis: 2000
      socket_timeout_millis: 30000
      connect_timeout_millis: 2000
      prefix:

## **********************************************************
##    Spring Settings (Redis、HBase)
## **********************************************************
spring:
  #redis 配置
  redis:
    host: 172.30.6.31
    port: 6379
  data:
    #HBase 配置
    hbase:
      quorum: 172.30.6.31:2181
      rootDir: file:///hbase
      nodeParent: /hbase

## **********************************************************
##    Datasource Settings
## **********************************************************
enable:
  datasource:
    type: elasticsearch


## **********************************************************
##   Plugins Settings (插件其他相关配置 详见tldw-analysis-plugins/README.md 参考文档)
## **********************************************************
plugin:
  #插件启动方式 dev or prod
  runMode: prod
  #插件包放置位置 Linux环境修改为对应路径形式 eg：./plugins C:\Users\zhangkehou\IdeaProjects\dev_jz_2.6.4_version_upgrade\santaizi\tldw-analysis-server\lib
  pluginPath: C:\\Users\\zhangkehou\\IdeaProjects\\dev_jz_2.6.4_version_upgrade\\santaizi\\tldw-analysis-server\\lib
  #  pluginPath: ./tldw-analysis-plugins
  #插件包配置文件路径
  #  pluginConfigFilePath: /opt/tldw/analysis/tldw-analysis-plugins
  pluginConfigFilePath:



